routes/web.php
<?php
use App\Passenger;
use App\Buses;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $bus = DB::table('buses')->get();
    $seats = DB::table('seats')->get();
    return view('welcome', ['bus' => $bus,'seats' => $seats]);
});

Route::get('booking/{bus_id}', function($bus_id)
{
      $seats = DB::table('seats')->get();
    $bus = DB::table('buses')->where('bus_id', $bus_id)->get();
       return view('booking', ['bus' => $bus,'seats' => $seats]);
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/reciept', 'PassengerController@indexnew')->name('reciept');
Route::get('ticket', function () {
    return view('ticket');
});
Route::post('/search','PassengerController@search');


// Operator Routes
Route::Resource('operator', 'OperatorController');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

//  Bus Route
Route::Resource('bus','BusController');

Route::post('destroy','BusController@destroy');
Route::get('edit-records','BusController@index');
Route::get('edit/{bus_id}','BusController@show');
Route::post('edit','BusController@edit');
Route::post('/store','BusController@store');

Route::Resource('user', 'UserController');

Route::Resource('driver', 'DriverController');
Route::post('addarrival/{bus_id}', 'DriverController@addarrival');
Route::post('savestop', 'DriverController@savestop');


Route::get('list', 'Profile@index');
Route::get('passenger', 'PassengerController@index');
Route::post('editpayment', 'PassengerController@editpayment');
Route::post('deletepass', 'PassengerController@deletepass');

Route::get('terminal', 'TerminalController@index');
Route::post('addterm', 'TerminalController@addterm');
Route::post('editterm', 'TerminalController@editterm');
Route::post('deleteterm', 'TerminalController@deleteterm');

Route::post('addpass', 'Profile@addpass');
Route::post('booking/addpass', 'Profile@addpass');
Route::post('adduser', 'Profile@adduser');
Route::post('edituser', 'Profile@edituser');
Route::post('deleteuser', 'Profile@deleteuser');
Route::post('pass', 'Profile@pass');




Route::post('deleteoperator','OperatorController@deleteoperator');
Route::get('edit-records','OperatorController@index');
Route::get('editoperator/{operator_id}','OperatorController@show');
Route::post('editoperator/{operator_id}','OperatorController@editoperator');
//  Region Route
Route::Resource('region','RegionController');


//  Sub Region Route
Route::Resource('sub-region','Sub_RegionController');

app/Region.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Region extends Model
{
    protected $table = 'regions';
    protected $fillable = ['region_name,region_code,status'];
    protected $primarykey = 'region_id';
}

app/Http/Controllers/RegionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Region;
use DB;

class RegionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $region = Region::get();

        return view('admin.regions.region-list', compact('region'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         // so here we will call the validation function okay
         $this->region_validation($request);
         $region_name = $request->get('region_name');
         $region_code = $request->get('region_code');
         // $status = $request->get('status');
             
         $insertRegion = [
             'region_name' => $region_name,
             'region_code' => $region_code,
             // 'status' => $status,
             'created_at' => \Carbon\carbon::now(),
             'updated_at' => \Carbon\carbon::now(),
         ];
        //  dd($insertRegion); // we will check okay if we are having all the data okay
         DB::table('regions')->insert( $insertRegion);
         Session::flash('msg', 'Region Register Successfully!');
         return redirect()->back();
 
         return view('admin.regions.region-list');
     }
 
     public function region_validation(){
         $rules = [  // this array okay to validate our buses input before insertation to our database
             'region_name' => 'required',
             'region_code' => 'required',
         ];
 
     }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/regions/add-region.blade.php
{{-- we will copy this modal and make some changes for the bus modal --}}
{{-- it's just a simple bootstrap modal okay  --}}
<!-- Modal -->
<div class="modal fade" id="exampleModalCenteraddbus" tabindex="-1" role="dialog" 
    aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="exampleModalLongTitle" align="center">
            <i class="glyphicon glyphicon-log-in">Add New Region</i></h2>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <form method="post" action="{{ route('region.store') }}" enctype="multipart/form-data">
                      {{ csrf_field() }}
                      <fieldset>
                      <div class="row">
                      <div class="col-md-6">
                          <div class="form-group">
                                <!-- <label for="exampleInputEmail1">Bus Name</label> -->
                                <input name="region_name"  class="form-control" aria-describedby="emailHelp"
                                 placeholder="Enter Region Name" type="text">
                          </div>
                          </div>
                          <div class="col-md-6">
                          <div class="form-group">
                                <!-- <label for="exampleInputEmail1">Bus Name</label> -->
                                <input name="region_code"  class="form-control" aria-describedby="emailHelp" 
                                placeholder="Enter Region Code" type="text">
                          </div>
                          </div>
                          </div>
                          <div class="col-md-3">
                          <div class="form-group">
                                <input name="status"  aria-describedby="emailHelp" type="checkbox">
                                <label for="exampleInputEmail1">Active</label>
                          </div>
              </div>
           </fieldset>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Register Region</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  
  
  
  

resources/views/admin/regions/region-list.blade.php
@extends('layouts.header')
@section('content') 
<!-- <div class="navbar-wrapper">
<a class="navbar-brand text-black " href="#pablo">Bus List</a>
 </div> -->
@include('admin.message')
<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
            <span class="pull-center">
            <a href="#" data-toggle="modal" data-target="#exampleModalCenteraddbus" 
            data-toggle="tooltip" type="button" class="btn btn-sm btn-primary">
            <i class="glyphicon glyphicon-plus"></i> Add New Region</a>
            </span>
            <br>
            <br>
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Region List</h4>
                  <h4 class="card-title pull-right">Today is: {{ date('d-m-Y', time()) }}</h4>
                  <p class="card-category"> Here is a subtitle for this table</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                  @if ( count($region) > 0 ) 
                    <table class="table">
                      <thead class=" text-primary">
                      <th>ID</th>
                    <th>Region Name</th>
                    <th>Region Code</th>
                    <th>Status</th>
                    <th>Created Date</th>
                    <th>Action</th>
                    </thead>
                    <tbody>
                    @foreach ( $region as $data )
                      <tr>
                        <td>{{ $data->region_id }}</td>
                        <td><a data-toggle="modal" data-target="#exampleModalCenterviewOperator
                            {{$data->region_id}}"data-toggle="tooltip">{{ $data->region_name }}</a></td>
                        <td>{{ $data->region_code }}</td>
                        <td>{{ $data->status }} 
                             {{-- echo" In Active"
                            @else
                            echo" Active" 
                            @endif --}}
                        </td>
                        <td>{{ $data->created_at }}</td>
                        <td>
                          <form action="{{ 'region.destroy' . $data->region_id }}" method="post">
                            {{ csrf_field() }}
                            {{ method_field('DELETE') }}
                            <input type="submit" name="submit" value="Edit" class="btn btn-sm btn-info" />
                            <input type="submit" name="submit" value="Delete" class="btn btn-sm btn-danger" />
                          </form>
                        </td>
                      </tr>
                    @endforeach
                </tbody>
              </table>
              @endif 
                 </div>
                </div>
              </div>
            </div>
            </div>
            </div>
            </div>
            @include('admin.regions.add-region')
            @include('admin.regions.add-region')
@endsection