routes/web.php
<?php
use App\Passenger;
use App\Buses;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $bus = DB::table('buses')->get();
    $seats = DB::table('seats')->get();
    return view('welcome', ['bus' => $bus,'seats' => $seats]);
});

Route::get('booking/{bus_id}', function($bus_id)
{
      $seats = DB::table('seats')->get();
    $bus = DB::table('buses')->where('bus_id', $bus_id)->get();
       return view('booking', ['bus' => $bus,'seats' => $seats]);
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/reciept', 'PassengerController@indexnew')->name('reciept');
Route::get('ticket', function () {
    return view('ticket');
});
Route::post('/search','PassengerController@search');


// Operator Routes
Route::Resource('operator', 'OperatorController');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

//  Bus Route
Route::Resource('bus','BusController');

Route::post('destroy','BusController@destroy');
Route::get('edit-records','BusController@index');
Route::get('edit/{bus_id}','BusController@show');
Route::post('edit','BusController@edit');
Route::post('/store','BusController@store');

Route::Resource('user', 'UserController');

Route::Resource('driver', 'DriverController');
Route::post('addarrival/{bus_id}', 'DriverController@addarrival');
Route::post('savestop', 'DriverController@savestop');


Route::get('list', 'Profile@index');
Route::get('passenger', 'PassengerController@index');
Route::post('editpayment', 'PassengerController@editpayment');
Route::post('deletepass', 'PassengerController@deletepass');

Route::get('terminal', 'TerminalController@index');
Route::post('addterm', 'TerminalController@addterm');
Route::post('editterm', 'TerminalController@editterm');
Route::post('deleteterm', 'TerminalController@deleteterm');

Route::post('addpass', 'Profile@addpass');
Route::post('booking/addpass', 'Profile@addpass');
Route::post('adduser', 'Profile@adduser');
Route::post('edituser', 'Profile@edituser');
Route::post('deleteuser', 'Profile@deleteuser');
Route::post('pass', 'Profile@pass');




Route::post('deleteoperator','OperatorController@deleteoperator');
Route::get('edit-records','OperatorController@index');
Route::get('editoperator/{operator_id}','OperatorController@show');
Route::post('editoperator/{operator_id}','OperatorController@editoperator');
//  Region Route
Route::Resource('region','RegionController');


//  Sub Region Route
Route::Resource('sub-region','Sub_RegionController');

app/Operator.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Operator extends Model
{
    protected $table = 'operators';
    protected $fillable = ['operator_name,operator_email,operator_phone,
                             operator_address,operator_logo,status'];
    protected $primarykey = 'operator_id';
}

app/Http/Controllers/OperatorController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Operator;
use DB;
use Session;
use App\Terminal;
class OperatorController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $operators = Operator::get();
        $terminal = Terminal::get();
        return view('admin.operators.operator-list', compact('operators','terminal'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // we are validating our inputs okay to avoid having error when inserting okay.
        $this->validate($request,[
            'operator_name' => 'required',
             'operator_email' => 'required',
             'operator_address' => 'required',
             'operator_phone' => 'required',
            //  'operator_logo' => 'image|max:2048',
        ]);

            $image =  $request->file('operator_logo');

            // $image_name = rand() . '.' . $image->getClientOriginalExtension();
            // $image->move(public_path('operator_images'), $image_name);

            $operators = new Operator;
            $operators->operator_name = $request->operator_name;
            $operators->operator_email = $request->operator_email;
            $operators->operator_address = $request->operator_address;
            $operators->operator_phone = $request->operator_phone;
            $operators->terminal_id = $request->terminal_id;
            $operators->operator_logo = " ";

                // dd($operators);
            $operators->save(); // THIS SAVE FUNCTION WILL SAVE THE DATA OKAY

            Session::flash('msg', 'Operator Adde
d Successfully!');
         return redirect()->back();
         return view('admin.operators.operator-list', compact('operators'));
// WE NEED TO GENERATE THIS CUSTOM FLASH MESSAGE OKAY. SO LET'S ADD THAT FIRST BEFORE INSERTING OKAY.
            $id = $request::get('operator_id');
            $operators = Operator::where('operator_id', $id);

            return view('admin.operators.operator-list', compact('operators'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
 public function editoperator(Request $request)
    {

     $this->validate($request,[
            'operator_name' => 'required',
             'operator_email' => 'required',
             'operator_address' => 'required',
             'operator_phone' => 'required',
     ]);

    $operator_name = $request->input('operator_name');
    $operator_email = $request->input('operator_email');
    $operator_address = $request->input('operator_address');
    $operator_phone = $request->input('operator_phone');
     $terminal_id = $request->input('terminal_id');
     $id = $request->input('id');
     
    


    DB::update('update operators set operator_name= ?,terminal_id=?,operator_email=?,operator_address=?,operator_phone=? where operator_id = ?',[$operator_name,$terminal_id,$operator_email,$operator_address,$operator_phone,$id]);
             Session::flash('msg', 'Operator Updated Successfully!');
         return redirect()->back();
         return view('admin.operators.operator-list', compact('operators'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }
 
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function deleteoperator(Request $request)
    {
        $id = $request->input('did');
        DB::delete('delete from operators where operator_id = ?',[$id]);
         Session::flash('msg', 'Operator Deleted Successfully!');
         return redirect()->back();
         return view('admin.operators.operator-list', compact('operators'));
    }
}

resources/views/admin/operators/add-operator.blade.php
{{-- we will copy this modal and make some changes for the bus modal --}}
{{-- it's just a simple bootstrap modal okay  --}}
<!-- Modal -->
<div class="modal fade" id="exampleModalCenteraddbus" tabindex="-1" role="dialog" 
    aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="exampleModalLongTitle" align="center">
            <i class="glyphicon glyphicon-log-in">Add New Operator</i></h2>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <form method="post" action="{{ route('operator.store') }}" enctype="multipart/form-data">
                      {{ csrf_field() }}
                      <fieldset>
                      <div class="row">
                      <div class="col-md-6">
                          <div class="form-group">
                                <!-- <label for="exampleInputEmail1">Bus Name</label> -->
                                <input name="operator_name"  class="form-control" aria-describedby="emailHelp"
                                 placeholder="Enter Operator Name" type="text">
                          </div>
                          </div>
                          <div class="col-md-6">
                          <div class="form-group">
                                <!-- <label for="exampleInputEmail1">Bus Name</label> -->
                                <input name="operator_email"  class="form-control" aria-describedby="emailHelp" 
                                placeholder="Enter Email" type="email">
                          </div>
                          </div>
                          </div>
                          <div class="form-group">
                                <!-- <label for="exampleInputEmail1">Bus Name</label> -->
                                <input name="operator_phone"  class="form-control" aria-describedby="emailHelp"
                                 placeholder="Enter Mobile Number" type="text">
                          </div>
                          <div class="form-group">
                                <!-- <label for="exampleInputPassword1">Seat No</label> -->
                                <textarea name="operator_address" rows="2" cols="20" class="form-control" 
                                placeholder="Enter Operator Address" type="text"></textarea>
                          </div>
                          <div class="form-group">
                                <!-- <label for="exampleInputPassword1">Seat No</label> -->
                                <select name="terminal_id" class="form-control">
                                    <option value="">Select Terminal</option>
                                    @foreach ($terminal as $terminals)
                                    <option value="{{$terminals->terminal_id}}">{{$terminals->terminal_name}}</option>
                                    @endforeach
                                </select>
                          </div>
                          {{-- <div class="form-group">
                                <!-- <label for="exampleInputPassword1">Seat No</label> -->
                                <textarea name="operator_description" rows="2" cols="20" class="form-control" 
                                placeholder="Enter Operator Description" type="text"></textarea>
                          </div> --}}
              <!--            <div class="col-md-3">-->
              <!--            <div class="form-group">-->
              <!--                  <input name="status"  aria-describedby="emailHelp" type="checkbox">-->
              <!--                  <label for="exampleInputEmail1">Active</label>-->
              <!--            </div>-->
              <!--</div>-->
            <!--  <div class="row">-->
            <!--    <div class="col-md-12">-->
            <!--            <label class="control-label">Image</label>-->
            <!--            <input type="file" name="operator_logo">-->
            <!--    </div>-->
            <!--</div>-->
                      </fieldset>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Register Operator</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  
  
  
  

resources/views/admin/operators/delete-operator.blade.php
{{-- we will copy this modal and make some changes for the bus modal --}}
{{-- it's just a simple bootstrap modal okay  --}}
<!-- Modal -->
<div class="modal fade" id="exampleModalCenterdelete" tabindex="-1" role="dialog" 
    aria-labelledby="exampleModalCenterdelete" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="exampleModalLongTitle" align="center">
            <i class="glyphicon glyphicon-log-in">Delete</i></h2>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <p>Are you sure you want to delete this data?</p>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <a href="deleteoperator/{{ $data->operator_id ?? 'empty'}}"><button type="submit" class="btn btn-primary">Delete Bus</button></a>
          </form>
        </div>
      </div>
    </div>
  </div>
  
  
  
  

resources/views/admin/operators/operator-list.blade.php
@extends('layouts.header')
@section('content') 
<!-- <div class="navbar-wrapper">
<a class="navbar-brand text-black " href="#pablo">Bus List</a>
 </div> -->
@include('admin.message')
<div class="content">
        <div class="container-fluid">
          <div class="row">
            <div class="col-md-12">
            <span class="pull-center">
            <a href="#" data-toggle="modal" data-target="#exampleModalCenteraddbus" 
            data-toggle="tooltip" type="button" class="btn btn-sm btn-primary">
            <i class="glyphicon glyphicon-plus"></i> Add New Operator</a>
            </span>
            <br>
            <br>
              <div class="card">
                <div class="card-header card-header-primary">
                  <h4 class="card-title ">Operators List</h4>
                  <h4 class="card-title pull-right">Today is: {{ date('d-m-Y', time()) }}</h4>
                  <p class="card-category"> Here is a subtitle for this table</p>
                </div>
                <div class="card-body">
                  <div class="table-responsive">
                  @if ( count($operators) > 0 ) 
                    <table class="table">
                      <thead class=" text-primary">
                    <th class="rowc">Operator Name</th>
                    <th class="rowc">Email</th>
                    <th class="rowc">Phone</th>
                    <th class="rowc">Address</th>
                    <th>Action</th>
                    </thead>
                    <tbody>
                    @foreach ( $operators as $data )
                     @if ($data->terminal_id == Auth::user()->terminal_id || Auth::user()->role== 'Super Admin')
                      <tr>
                        <td class="rowl"><a data-toggle="modal" data-target="#exampleModalCenterviewOperator
                            {{$data->operator_id}}"data-toggle="tooltip">{{ $data->operator_name }}</a></td>
                        <td class="rowl">{{ $data->operator_email }}</td>
                        <td class="rowl">{{ $data->operator_phone }}</td>
                        <!-- <td>{{ $data->operator_address }}</td> -->
                        <!-- <td>{{ $data->operator_description }}</td> -->
                        <td class="rowl">{{ $data->operator_address }}</td>
                        <td>

                            <button data-toggle="modal" data-target="#exampleModalCentereditbus" class="btn btn-sm btn-info myBtn" id="myBtn"  data-value="{{ $data->operator_id }}">Edit</button>
                             <button data-toggle="modal" data-target="#exampleModalCenterdeletebus" class="btn btn-sm btn-danger myBtnd" id="myBtnd"  data-valued="{{ $data->operator_id }}" >Delete</button>

                        </td>
                      </tr>
                      @endif
                    @endforeach
                </tbody>
              </table>
              @endif 
              <button class="btn btn-sm btn-info" onclick="exportTableToCSV('members.csv')">Export CSV File</button>
                 </div>
                </div>
              </div>
            </div>
            </div>
            </div>
            </div>
            @include('admin.operators.add-operator')
            @include('admin.operators.delete-operator')
@endsection

<div class="modal fade" id="exampleModalCentereditbus" tabindex="-1" role="dialog" 
    aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="exampleModalLongTitle" align="center">
            <i class="glyphicon glyphicon-log-in">Edit Operator</i></h2>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <form method="post" action="editoperator" enctype="multipart/form-data">
                      {{ csrf_field() }}
                      <fieldset>
                      <div class="row">
                      <div class="col-md-6">
                          <div class="form-group">
                                <!-- <label for="exampleInputEmail1">Bus Name</label> -->
                                <input name="operator_name"  class="form-control" aria-describedby="emailHelp"
                                 placeholder="Enter Operator Name" type="text">
                          </div>
                          </div>
                          <div class="col-md-6">
                          <div class="form-group">
                                <!-- <label for="exampleInputEmail1">Bus Name</label> -->
                                <input name="operator_email"  class="form-control" aria-describedby="emailHelp" 
                                placeholder="Enter Email" type="email">
                          </div>
                          </div>
                          </div>
                          <div class="form-group">
                                <!-- <label for="exampleInputEmail1">Bus Name</label> -->
                                <input name="operator_phone"  class="form-control" aria-describedby="emailHelp"
                                 placeholder="Enter Mobile Number" type="text">
                          </div>
                          <div class="form-group">
                                <!-- <label for="exampleInputPassword1">Seat No</label> -->
                                <textarea name="operator_address" rows="2" cols="20" class="form-control" 
                                placeholder="Enter Operator Address" type="text"></textarea>
                          </div>
                          <div class="form-group">
                                <!-- <label for="exampleInputPassword1">Seat No</label> -->
                                <select name="terminal_id" class="form-control">
                                    <option value="">Select Terminal</option>
                                    @foreach ($terminal as $terminals)
                                    <option value="{{$terminals->terminal_id}}">{{$terminals->terminal_name}}</option>
                                    @endforeach
                                </select>
                          </div>
                          {{-- <div class="form-group">
                                <!-- <label for="exampleInputPassword1">Seat No</label> -->
                                <textarea name="operator_description" rows="2" cols="20" class="form-control" 
                                placeholder="Enter Operator Description" type="text"></textarea>
                          </div> --}}
<!--                           <div class="col-md-3">
                          <div class="form-group">
                                <input name="status"  aria-describedby="emailHelp" type="checkbox">
                                <label for="exampleInputEmail1">Active</label>
                          </div>
              </div> -->
          <!--     <div class="row">
                <div class="col-md-12">
                        <label class="control-label">Image</label>
                        <input type="file" name="operator_logo">
                </div>
            </div> -->
                      </fieldset>
        </div>
        <input type="hidden" name="id" id="id">
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <a href="editoperator/{{ $data->operator_id }}"><button type="submit" class="btn btn-primary">Update Operator</button></a>
          </form>
        </div>
      </div>
    </div>
  </div>
  
  <!--DELETE-->
     <div class="modal fade" id="exampleModalCenterdeletebus" tabindex="-1" role="dialog" 
    aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h2 class="modal-title" id="exampleModalLongTitle" align="center">
            <i class="glyphicon glyphicon-log-in">Delete</i></h2>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
        <form method="post" action="deleteoperator" enctype="multipart/form-data">
            {{ csrf_field() }}
            <p>Are you sure you want to delete this data?</p>
            <input type="hidden" name="did" id="did">
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
          <a href="deleteuser/"><button type="submit" class="btn btn-primary">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script>
$(document).ready(function(){
     $(".myBtn").click(function(){
       var idd=$(this).attr("data-value");
       $( "#id" ).val( idd );
      
    });
    $(".myBtnd").click(function(){
       var idd=$(this).attr("data-valued");
       $( "#did" ).val( idd );
      
    });
});
</script>
  <script>
  function exportTableToCSV(filename) {
    var csv = [];
    var rows = document.querySelectorAll("table tr");
    
    for (var i = 0; i < rows.length; i++) {
        var row = [], cols = rows[i].querySelectorAll(".rowl, .rowc");
        
        for (var j = 0; j < cols.length; j++) 
            row.push(cols[j].innerText);
        
        csv.push(row.join(","));        
    }

    // Download CSV file
    downloadCSV(csv.join("\n"), filename);
}

function downloadCSV(csv, filename) {
    var csvFile;
    var downloadLink;

    // CSV file
    csvFile = new Blob([csv], {type: "text/csv"});

    // Download link
    downloadLink = document.createElement("a");

    // File name
    downloadLink.download = filename;

    // Create a link to the file
    downloadLink.href = window.URL.createObjectURL(csvFile);

    // Hide download link
    downloadLink.style.display = "none";

    // Add the link to DOM
    document.body.appendChild(downloadLink);

    // Click download link
    downloadLink.click();
}
</script>