routes/web.php
<?php
use App\Passenger;
use App\Buses;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    $bus = DB::table('buses')->get();
    $seats = DB::table('seats')->get();
    return view('welcome', ['bus' => $bus,'seats' => $seats]);
});

Route::get('booking/{bus_id}', function($bus_id)
{
      $seats = DB::table('seats')->get();
    $bus = DB::table('buses')->where('bus_id', $bus_id)->get();
       return view('booking', ['bus' => $bus,'seats' => $seats]);
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/reciept', 'PassengerController@indexnew')->name('reciept');
Route::get('ticket', function () {
    return view('ticket');
});
Route::post('/search','PassengerController@search');


// Operator Routes
Route::Resource('operator', 'OperatorController');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

//  Bus Route
Route::Resource('bus','BusController');

Route::post('destroy','BusController@destroy');
Route::get('edit-records','BusController@index');
Route::get('edit/{bus_id}','BusController@show');
Route::post('edit','BusController@edit');
Route::post('/store','BusController@store');

Route::Resource('user', 'UserController');

Route::Resource('driver', 'DriverController');
Route::post('addarrival/{bus_id}', 'DriverController@addarrival');
Route::post('savestop', 'DriverController@savestop');


Route::get('list', 'Profile@index');
Route::get('passenger', 'PassengerController@index');
Route::post('editpayment', 'PassengerController@editpayment');
Route::post('deletepass', 'PassengerController@deletepass');

Route::get('terminal', 'TerminalController@index');
Route::post('addterm', 'TerminalController@addterm');
Route::post('editterm', 'TerminalController@editterm');
Route::post('deleteterm', 'TerminalController@deleteterm');

Route::post('addpass', 'Profile@addpass');
Route::post('booking/addpass', 'Profile@addpass');
Route::post('adduser', 'Profile@adduser');
Route::post('edituser', 'Profile@edituser');
Route::post('deleteuser', 'Profile@deleteuser');
Route::post('pass', 'Profile@pass');




Route::post('deleteoperator','OperatorController@deleteoperator');
Route::get('edit-records','OperatorController@index');
Route::get('editoperator/{operator_id}','OperatorController@show');
Route::post('editoperator/{operator_id}','OperatorController@editoperator');
//  Region Route
Route::Resource('region','RegionController');


//  Sub Region Route
Route::Resource('sub-region','Sub_RegionController');

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/main.css') }}" rel="stylesheet">
</head>
<style type="text/css">
    #app{max-width: 40%;margin:auto;justify-content:center;text-align: center;background-color: rgba(101, 155, 231, 0.65);padding:50px;margin-top:100px;border-radius:10px;}
    #app li{text-decoration:none;}
     #app input{
        padding:10px 30px;
         margin-top:10px;
     }
     #app label{
        font-size: 18px;
       
     }

     #app button{
        font-size: 18px;
        padding:5px 30px;
        margin-bottom: 20px;
       
     }

     .form-group{
        margin-top:20px;
     }
     .card-header{
        font-size: 32px;
        font-weight: bold;
        text-transform: uppercase;
        font-family: "Inter";
     }
</style>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest<!-- 
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif -->
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/headernew.blade.php
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="{{ asset('back-end/assets/demo/demo.css" rel="stylesheet')}}" />
     <link href="{{ asset('css/main.css" rel="stylesheet')}}" />
     <link href="{{ asset('back-end/assets/css/material-dashboard.css?v=2.1.1')}}" rel="stylesheet" />
      <link href="{{ asset('back-end/assets/css/main.css?v=2.1.1')}}" rel="stylesheet" />

</head>
<body>
<header>
<div class="header">
  <a href="http://kabayanebus.com/" class="logo" ><img style="max-width:120px;" src='http://kabayanebus.com/Logo.png'></a>
  <div class="header-right">
    <a href="{{ url('/') }}">Home</a>
    <a href="http://kabayanebus.com/ticket">Ticket</a>
    <a href="{{ route('login') }}">Login</a>
  </div>
</div>
</header>

</html>

resources/views/layouts/reciept.blade.php
<style>
  .main {
  background-image: url("https://images.unsplash.com/photo-1556742205-e10c9486e506?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60");
  color: #00cc65;
  width: 500px;
  padding-left: 25px;
  padding-top: 10rem;
}
</style>
<!-- partial:index.partial.html -->
<div id="html-content-holder" class="main">
        <h3 style="color: #3e4b51;">
            This is a demo
        </h3>
    </div>
    <a id="btn-Convert-Html2Image" href="#">Download</a>
    <br />
    <div id="previewImage" style="display: none;">
</div>
<!-- partial -->
  <script src='https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js'></script>
<script>
  $(document).ready(function () {
            var element = $("#html-content-holder"); // global variable
            var getCanvas; // global variable

            html2canvas(element, {
                onrendered: function (canvas) {
                    $("#previewImage").append(canvas);
                    getCanvas = canvas;
                }
            });

            $("#btn-Convert-Html2Image").on('click', function () {
                var imgageData = getCanvas.toDataURL("image/png");
                // Now browser starts downloading it instead of just showing it
                var newData = imgageData.replace(/^data:image\/png/, "data:application/octet-stream");
                $("#btn-Convert-Html2Image").attr("download", "your_pic_name.png").attr("href", newData);
            });
        });
</script>

resources/views/layouts/sidebar.blade.php
<div class="sidebar-wrapper">
  @if (Auth::user()->role =='Admin' || Auth::user()->role =='Super Admin')
    <ul class="nav">
      <li class="nav-item ">
        <a class="nav-link" href="./list">
          <i class="material-icons">person</i>
          <p>User Profile</p>
        </a>
      </li>
      <li class="nav-item ">
      <a class="nav-link" href="{{route('operator.index')}}">
          <i class="material-icons">content_paste</i>
          <p>operators List</p>
        </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{{route('bus.index')}}">
          <i class="material-icons">library_books</i>
          <p>Buses List</p>
        </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="./passenger">
          <i class="material-icons">bubble_chart</i>
          <p>Passenger List</p>
        </a>
      </li>
     </ul>
 @endif
  @if (Auth::user()->role =='Dispatcher'   )
    <ul class="nav">
      <li class="nav-item ">
        <a class="nav-link" href="./list">
          <i class="material-icons">person</i>
          <p>User Profile</p>
        </a>
      </li>
      <li class="nav-item ">
      <a class="nav-link" href="{{route('operator.index')}}">
          <i class="material-icons">content_paste</i>
          <p>operators List</p>
        </a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{{route('bus.index')}}">
          <i class="material-icons">library_books</i>
          <p>Buses List</p>
        </a>
      </li>
     </ul>
 @endif
 @if (Auth::user()->role =='Super Admin' )
    <ul class="nav">
      <li class="nav-item ">
        <a class="nav-link" href="./terminal">
          <i class="material-icons">location_ons</i>
          <p>Terminal List</p>
        </a>
      </li>

    </ul>
  @endif
  @if (Auth::user()->role =='Driver' || Auth::user()->role =='Conductor' )
  <ul class="nav">
     <li class="nav-item ">
        <a class="nav-link" href="./driver">
          <i class="material-icons">location_ons</i>
          <p>Assignment</p>
        </a>
      </li>
  </ul>
  @endif
  
  </div>